import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import TanstackQueryProvider from "@/utils/Providers";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            // defaultTheme="light"
            // defaultTheme="system" //system, light, dark
            enableSystem
            disableTransitionOnChange
          >
            <TanstackQueryProvider >
              {children}
              <Toaster richColors />
            </TanstackQueryProvider>
          </ThemeProvider>  
      </body>
    </html>
  );
}
